### ISSUE TITLE
Generate JS-mapping with minOccurs/maxOccurs

### ISSUE THREAD

**Issue by martinpfannemueller** [highsource/jsonix-schema-compiler#33]
Referring stackoverflow question:
http://stackoverflow.com/questions/29256036/jsonix-get-restrictions-and-default-value-for-properties

**Comment by hokkos** [comment]
I am using the unmarshalled XSD for that, using https://github.com/highsource/w3c-schemas

**Comment by highsource** [comment]
I think this should be possible in most (but not all) cases.

**Comment by highsource** [comment]
This should be implemented in `2.3.7`, please test. I'd be grateful for feedback if it works for you.

**Comment by martinpfannemueller** [comment]
It works like a charm, thanks a lot!
