### ISSUE TITLE
Generate minOccurs/maxOccurs in JSON Schema

### ISSUE THREAD

**Issue by highsource** [highsource/jsonix-schema-compiler#40]

**Comment by pdesmarets** [comment]
I am also interested in this feature!!  Do you have an update?  Thx!

**Comment by highsource** [comment]
Not yet, but probably one of the next features here. I was also missing this.

**Comment by highsource** [comment]
This should be implemented in `2.3.7`, please test. I'd be grateful for feedback if it works for you.
