### ISSUE TITLE
Generate "required" : [...] for XSD use="required"  

### ISSUE THREAD

**Issue by pdesmarets** [highsource/jsonix-schema-compiler#50]
Another observation.  it appears to me that the above is not currently supported either?  Is this a difficult one, or one that can be added along with min/maxOccurs, etc...?

Cheers

**Comment by highsource** [comment]
No, that should be pretty doable together with min/maxOccurs.

**Comment by highsource** [comment]
Thanks for filing issues. :)

**Comment by pdesmarets** [comment]
Sorry for that.  It's a sign that your work if useful ;-)

Looking forward to the new features!  Cheers

**Comment by highsource** [comment]
This should be implemented in `2.3.7`, please test. I'd be grateful for feedback if it works for you.
