### ISSUE TITLE
Simple type "inputOutputAccessTypes" was not mapped to Enum due to EnumMemberSizeCap limit. Facets count: 357, current limit: 256. You can use customization attribute "typesafeEnumMaxMembers" to extend the limit.

### ISSUE THREAD

**Issue by coderextreme** [highsource/jsonix-schema-compiler#51]
Running the compiler on X3D 3.4 xsd I got the following error:

$ java -jar /Users/johncarlson/Source/jsonix-schema-compiler/full/target/jsonix-schema-compiler-full-2.3.7-SNAPSHOT.jar x3d-3.4.xsd 
[WARNING] Simple type "inputOutputAccessTypes" was not mapped to Enum due to EnumMemberSizeCap limit. Facets count: 357, current limit: 256. You can use customization attribute "typesafeEnumMaxMembers" to extend the limit.
  line 1370 of file:/Users/johncarlson/Downloads/www.web3d.org/specifications/x3d-3.4.xsd

Here's how I fixed it:

$ cat x3d.xjb 
```xml
<?xml version="1.0" ?>
<bindings version="1.0" xmlns="http://java.sun.com/xml/ns/jaxb" schemaLocation="x3d-3.4.xsd">
        <bindings>
            <globalBindings typesafeEnumMaxMembers="600"/>
        </bindings>
</bindings>
```
$ java -jar jsonix-schema-compiler/full/target/jsonix-schema-compiler-full-2.3.7-SNAPSHOT.jar x3d-3.4.xsd  -b x3d.xjb 

I haven't verified the schema yet, because I have no documents which match the schema yet.  Good luck

**Comment by highsource** [comment]
Hi John,

this is correct and your sollution is the right one. Is it just Q&A or do you happen to have an issue here?

Best wishes,
Alexey

**Comment by coderextreme** [comment]
No issue, just information that people might be able to use if they run into problems with a particular XML schema.

**Comment by highsource** [comment]
Thank you, documented:

https://github.com/highsource/jsonix-schema-compiler/wiki/EnumMemberSizeCap-Limit
