### ISSUE TITLE
Generate "default" : [...] for XSD default= boolean/string/value ... 

### ISSUE THREAD

**Issue by pdesmarets** [highsource/jsonix-schema-compiler#52]
Sorry to pile these up.  If I'm not mistaken, it appears to me that the above is not currently supported either?  Is this a difficult one, or one that can be added along with min/maxOccurs, etc...?

Cheers

**Comment by highsource** [comment]
Yes, see #39 .

**Comment by pdesmarets** [comment]
Oops, sorry about that.  My bad.

**Comment by highsource** [comment]
No worries, it's ok. :)
