### ISSUE TITLE
Add option for full baseTypeInfo

### ISSUE THREAD

**Issue by martinpfannemueller** [highsource/jsonix-schema-compiler#54]
In earlier releases the baseTypeInfo got resolved to the full path like this:
```
...
baseTypeInfo: com.example.XMLType,
...
```

In the last couple releases it gets this:
```
...
baseTypeInfo: .XMLType,
...
```

Is it somehow possible to get the full path back?

**Comment by highsource** [comment]
You can access this information via the `name` property of the class info. Something like:

```javascript
var context = new Jsonix.Context([ PO ]);
var itemsClassInfo = context.getTypeInfoByName("PO.Items");
test.equal('PO.Items, itemPropertyInfo.name);
```

The mapping name is omitted in mappings for brevity.

**Comment by martinpfannemueller** [comment]
Thanks a lot for the hint! You helped me a lot as always :+1:
