### ISSUE TITLE
Support for RelaxNG schemas or SVG.xsd?

### ISSUE THREAD

**Issue by carlsonsolutiondesign** [highsource/jsonix-schema-compiler#56]
I note that the SVG.xsd is not compliant with XSD schema.  Would it be possible enhance Jsonix to support RelaxNG schemas?  Thanks!

**Comment by highsource** [comment]
I'm afraid this won't happen.

Jsonix Schema Compiler relies on XJC, the JAXB Schema Compiler. It is described to have RelaxNG support, but the last time I tried, I've spent a few hours trying to compile a RelaxNG, failing with different deep-reaching errors, for example:

* https://java.net/jira/browse/JAXB-1065
* https://java.net/jira/browse/JAXB-1066
* https://java.net/jira/browse/JAXB-1067

Finally I was confident that it just does not work and filed this issue:

* https://java.net/jira/browse/JAXB-1068

For the Jsonix Schema Compiler is means that the underlying technology does not support RelaxNG. I will definitely not have resources to implement this support. So I'm sorry to mark this as "won't fix" but I have no options here.

I think the best approach for RelaxNG schemas would be using something like [Trang](http://www.thaiopensource.com/relaxng/trang.html) to convert them to XSD and then compile them. However it is also not trivial.

Specifically for SVG I think the story is a bit more complicated as there seems to be no formal schema for SVG:

* http://stackoverflow.com/questions/3510986/where-can-i-find-a-valid-svg-xml-schema-for-ecore-generation

There's DTD for SVG 1.1 and RelaxNG for SVG 1.2 Tiny but that's it.

BTW [w3c-schemas](https://github.com/highsource/w3c-schemas) would be the target project for SVG mappings.
