### ISSUE TITLE
pattern in XML schema don't get carried over into JSON schema

### ISSUE THREAD

**Issue by coderextreme** [highsource/jsonix-schema-compiler#59]
I may have filed this in the wrong place.  See: https://github.com/highsource/jsonix/issues/106

I'm trying to carry over the regular expression patterns from this XML schema below into JSON schema so I can validate JSON documents. Does JSON schema handle regular expressions? If so, can Jsonix? If not, can we create an extension to JSON schema that Jsonix can support? Thanks!

http://www.web3d.org/specifications/x3d-3.4.xsd

**Comment by highsource** [comment]
Hi,

I think JSON Schema supportes patterns (regular expressions):

http://spacetelescope.github.io/understanding-json-schema/reference/string.html#regular-expressions

The compiler does not support this, however.
If JSON Schema and XML Schema have identical regex syntaxes then it will be
possible, if not then not (as I most probably won't be able to translate
regex languages).

Best wishes,
Alexey

**Comment by coderextreme** [comment]
I found this: https://home.java.net/forum/topic/glassfish/metro-and-jaxb/jaxb-plugin-generate-bean-validation-annotations-jsr-303  JSON Schema isn't a standard.  We may need to convince Ajv or another JSON Schema validator to support the XSD or JAXB regular expressions.  Also where I found the link: http://stackoverflow.com/questions/20220824/jaxb-generated-simple-type-missing-restriction

**Comment by highsource** [comment]
Thanks for the links, I have actually quite a good understanding of how to read XSD facets from the XSOM model, that is not an issue.

JSON schema is not a standard de-jure but it's a well-defined specification. I wouldn't say we have an issue with standardisation here.

The problem with regexes is not persuasion. JSON Schema definitely uses JS regexes. If XSD regexes aren't compatible with JS, they have to be translated. This might be a lot of work, and it is definitely not in scope of JSON Schema validators.

Let's first check if they are compatible.

**Comment by highsource** [comment]
Please see the answers in this SO question:

http://stackoverflow.com/questions/33482031/are-xml-schema-regular-expressions-compatible-to-javascript-ecmascript-regular-e

It appears that XML Schema regular expressions are not compatible to the JS regular expressions.

This means we (unfortunatelly) can't carry XML Schema regular expressions to JSON Schema.

Translating regular expressions would be too hard to implement so I'll have to close this with `wontfix`. Sorry.
