### ISSUE TITLE
Support default values for attributes of `anySimpleType`

### ISSUE THREAD

**Issue by st-sloth** [highsource/jsonix-schema-compiler#86]
Support of default values was largely implemented in #32.

But for attribute declarations of `anySimpleType` with `default` attribute, the resulting mappings don't have `defaultValue` property.

It was suggested in #32 to just copy the string value.

[This PR](#85) adds example attribute declaration in the test schema.

**Comment by highsource** [comment]
@st-sloth This should work now, please give it a try.

**Comment by ghost** [comment]
Yes, it works perfectly, thank you!
