### ISSUE TITLE
Support default values for attributes of named simple types

### ISSUE THREAD

**Issue by st-sloth** [highsource/jsonix-schema-compiler#87]
Support of default values was largely implemented in #32.

But for some attribute declarations of a named simple type with `default` attribute, the resulting mappings don't have `defaultValue` property.

For example, [attributes of a named simple type restricted with pattern](https://github.com/highsource/jsonix-schema-compiler/pull/85/files#diff-e6b371702fc6fb713ebbd41ea6bad0edR162) have `defaultValue` in the mappings. But [attributes of a named simple type restricted with enumeration](https://github.com/highsource/jsonix-schema-compiler/pull/85/files#diff-e6b371702fc6fb713ebbd41ea6bad0edR154) do not.

[This PR](#85) adds example attribute declarations in the test schema.

**Comment by highsource** [comment]
This should also work now. I get `defaultValue` in all four fields.

**Comment by highsource** [comment]
@st-sloth Please check if this works for you.

**Comment by ghost** [comment]
Yes, it works perfectly now too, thank you!
