### ISSUE TITLE
"<annotation>" not included in json schema?

### ISSUE THREAD

**Issue by caleblawrence** [highsource/jsonix-schema-compiler#89]
Hello, 

I was wondering if you could help with this. I have some annotations in my XSD file like so: 
```xml 
<complexType name="DictionaryType">
      <annotation>
          <appinfo>
        	<dictionary>tgap</dictionary>
          </appinfo>
           <documentation>
               <name>tgap Application Dictionary</name>
               <description>test</description>
             </documentation>
         </annotation>
</complexType>
```
However this annotation is not brought into the json schema when I run:  java -jar jsonix-schema-compiler-full-2.3.9.jar -generateJsonSchema -p PO schema.xsd

I didn't see anything in the docs to help with this. Any ideas on how I can get this included in the json schema?

**Comment by highsource** [comment]
Jsonix Schema Compiler does not do anything with XML Schema annotations.

What would you actually expect to be generated?

**Comment by caleblawrence** [comment]
Ok good to know - thanks for the help. 
I guess I would expect it to treat it like any other element but that wouldn't make that much sense...
